events {
    worker_connections 1024;
}

http {
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    # Только HTTP — используется при первом запуске для получения SSL-сертификата
    server {
        listen 80;
        server_name raemon.ru www.raemon.ru;

        # ACME-challenge для Let's Encrypt
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
